<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/gtfs-realtime.proto

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An alert, indicating some sort of incident in the public transit network.
 *
 * Generated from protobuf message <code>google.transit.realtime.Alert</code>
 */
class Alert extends \Google\Protobuf\Internal\Message
{
    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TimeRange active_period = 1;</code>
     */
    private $active_period;
    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.EntitySelector informed_entity = 5;</code>
     */
    private $informed_entity;
    /**
     * optional Cause cause = 6 [default = UNKNOWN_CAUSE];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Cause cause = 6;</code>
     */
    protected $cause = 0;
    /**
     * optional Effect effect = 7 [default = UNKNOWN_EFFECT];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Effect effect = 7;</code>
     */
    protected $effect = 0;
    /**
     * The URL which provides additional information about the alert.
     * optional TranslatedString url = 8;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString url = 8;</code>
     */
    protected $url = null;
    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     * optional TranslatedString header_text = 10;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString header_text = 10;</code>
     */
    protected $header_text = null;
    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * optional TranslatedString description_text = 11;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString description_text = 11;</code>
     */
    protected $description_text = null;
    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_header_text = 12;</code>
     */
    protected $tts_header_text = null;
    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_description_text = 13;</code>
     */
    protected $tts_description_text = null;
    /**
     * Generated from protobuf field <code>.google.transit.realtime.Alert.SeverityLevel severity_level = 14;</code>
     */
    protected $severity_level = 0;
    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedImage image = 15;</code>
     */
    protected $image = null;
    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString image_alternative_text = 16;</code>
     */
    protected $image_alternative_text = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Transit\Realtime\TimeRange[]|\Google\Protobuf\Internal\RepeatedField $active_period
     *           Time when the alert should be shown to the user. If missing, the
     *           alert will be shown as long as it appears in the feed.
     *           If multiple ranges are given, the alert will be shown during all of them.
     *     @type \Google\Transit\Realtime\EntitySelector[]|\Google\Protobuf\Internal\RepeatedField $informed_entity
     *           Entities whose users we should notify of this alert.
     *     @type int $cause
     *           optional Cause cause = 6 [default = UNKNOWN_CAUSE];
     *     @type int $effect
     *           optional Effect effect = 7 [default = UNKNOWN_EFFECT];
     *     @type \Google\Transit\Realtime\TranslatedString $url
     *           The URL which provides additional information about the alert.
     *           optional TranslatedString url = 8;
     *     @type \Google\Transit\Realtime\TranslatedString $header_text
     *           Alert header. Contains a short summary of the alert text as plain-text.
     *           optional TranslatedString header_text = 10;
     *     @type \Google\Transit\Realtime\TranslatedString $description_text
     *           Full description for the alert as plain-text. The information in the
     *           description should add to the information of the header.
     *           optional TranslatedString description_text = 11;
     *     @type \Google\Transit\Realtime\TranslatedString $tts_header_text
     *           Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *     @type \Google\Transit\Realtime\TranslatedString $tts_description_text
     *           Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *     @type int $severity_level
     *     @type \Google\Transit\Realtime\TranslatedImage $image
     *           TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     *           The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *     @type \Google\Transit\Realtime\TranslatedString $image_alternative_text
     *           Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     *           or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     *           NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TimeRange active_period = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivePeriod()
    {
        return $this->active_period;
    }

    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TimeRange active_period = 1;</code>
     * @param \Google\Transit\Realtime\TimeRange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivePeriod($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TimeRange::class);
        $this->active_period = $arr;

        return $this;
    }

    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.EntitySelector informed_entity = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInformedEntity()
    {
        return $this->informed_entity;
    }

    /**
     * Entities whose users we should notify of this alert.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.EntitySelector informed_entity = 5;</code>
     * @param \Google\Transit\Realtime\EntitySelector[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInformedEntity($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\EntitySelector::class);
        $this->informed_entity = $arr;

        return $this;
    }

    /**
     * optional Cause cause = 6 [default = UNKNOWN_CAUSE];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Cause cause = 6;</code>
     * @return int
     */
    public function getCause()
    {
        return $this->cause;
    }

    /**
     * optional Cause cause = 6 [default = UNKNOWN_CAUSE];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Cause cause = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCause($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\Cause::class);
        $this->cause = $var;

        return $this;
    }

    /**
     * optional Effect effect = 7 [default = UNKNOWN_EFFECT];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Effect effect = 7;</code>
     * @return int
     */
    public function getEffect()
    {
        return $this->effect;
    }

    /**
     * optional Effect effect = 7 [default = UNKNOWN_EFFECT];
     *
     * Generated from protobuf field <code>.google.transit.realtime.Alert.Effect effect = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setEffect($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\Effect::class);
        $this->effect = $var;

        return $this;
    }

    /**
     * The URL which provides additional information about the alert.
     * optional TranslatedString url = 8;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString url = 8;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getUrl()
    {
        return $this->url;
    }

    public function hasUrl()
    {
        return isset($this->url);
    }

    public function clearUrl()
    {
        unset($this->url);
    }

    /**
     * The URL which provides additional information about the alert.
     * optional TranslatedString url = 8;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString url = 8;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->url = $var;

        return $this;
    }

    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     * optional TranslatedString header_text = 10;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString header_text = 10;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getHeaderText()
    {
        return $this->header_text;
    }

    public function hasHeaderText()
    {
        return isset($this->header_text);
    }

    public function clearHeaderText()
    {
        unset($this->header_text);
    }

    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     * optional TranslatedString header_text = 10;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString header_text = 10;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setHeaderText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->header_text = $var;

        return $this;
    }

    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * optional TranslatedString description_text = 11;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString description_text = 11;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getDescriptionText()
    {
        return $this->description_text;
    }

    public function hasDescriptionText()
    {
        return isset($this->description_text);
    }

    public function clearDescriptionText()
    {
        unset($this->description_text);
    }

    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * optional TranslatedString description_text = 11;
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString description_text = 11;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setDescriptionText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->description_text = $var;

        return $this;
    }

    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_header_text = 12;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getTtsHeaderText()
    {
        return $this->tts_header_text;
    }

    public function hasTtsHeaderText()
    {
        return isset($this->tts_header_text);
    }

    public function clearTtsHeaderText()
    {
        unset($this->tts_header_text);
    }

    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the text-to-speech version of header_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_header_text = 12;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsHeaderText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->tts_header_text = $var;

        return $this;
    }

    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_description_text = 13;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getTtsDescriptionText()
    {
        return $this->tts_description_text;
    }

    public function hasTtsDescriptionText()
    {
        return isset($this->tts_description_text);
    }

    public function clearTtsDescriptionText()
    {
        unset($this->tts_description_text);
    }

    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This field is the text-to-speech version of description_text.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString tts_description_text = 13;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsDescriptionText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->tts_description_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.transit.realtime.Alert.SeverityLevel severity_level = 14;</code>
     * @return int
     */
    public function getSeverityLevel()
    {
        return $this->severity_level;
    }

    /**
     * Generated from protobuf field <code>.google.transit.realtime.Alert.SeverityLevel severity_level = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setSeverityLevel($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\Alert\SeverityLevel::class);
        $this->severity_level = $var;

        return $this;
    }

    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedImage image = 15;</code>
     * @return \Google\Transit\Realtime\TranslatedImage|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect of a detour, station closure, etc. The image must enhance the understanding of the alert. Any essential information communicated within the image must also be contained in the alert text.
     * The following types of images are discouraged : image containing mainly text, marketing or branded images that add no additional information.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedImage image = 15;</code>
     * @param \Google\Transit\Realtime\TranslatedImage $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedImage::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString image_alternative_text = 16;</code>
     * @return \Google\Transit\Realtime\TranslatedString|null
     */
    public function getImageAlternativeText()
    {
        return $this->image_alternative_text;
    }

    public function hasImageAlternativeText()
    {
        return isset($this->image_alternative_text);
    }

    public function clearImageAlternativeText()
    {
        unset($this->image_alternative_text);
    }

    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image text - https://html.spec.whatwg.org/#alt.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
     *
     * Generated from protobuf field <code>.google.transit.realtime.TranslatedString image_alternative_text = 16;</code>
     * @param \Google\Transit\Realtime\TranslatedString $var
     * @return $this
     */
    public function setImageAlternativeText($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TranslatedString::class);
        $this->image_alternative_text = $var;

        return $this;
    }

}

